# Generated by Django 4.2.5 on 2023-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_over_time_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('beef_consumption', models.TextField(max_length=100)),
                ('pig_consumption', models.TextField(max_length=100)),
                ('poultry_consumption', models.TextField(max_length=100)),
                ('sheep_consumption', models.TextField(max_length=100)),
            ],
        ),
    ]
