# Generated by Django 4.2.5 on 2023-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_over_time_data',
            fields=[
                ('id', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('country', models.TextField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('beef_consumption', models.FloatField()),
                ('pig_consumption', models.FloatField()),
                ('poultry_consumption', models.FloatField()),
                ('sheep_consumption', models.FloatField()),
            ],
        ),
    ]
